# Generated by Django 4.2 on 2023-05-10 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('reply', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.topic')),
            ],
        ),
    ]
